### PR TITLE
Move bloc related APIs to comms package

### PR DESCRIPTION
**Pull request by iasiu**
- update changelog and pubspec version

- add bloc package

- add ListenerBloc, ListenerCubit and StateSender

- add tests

- extract ProductCountChangedMessage to seperate file

Related to #59

### CODE REVIEW

**Comment by iasiu** [comment]
in next PR I will remove them from `flutter_comms` package

**Review by bartekpacia — APPROVED** [review]
Nice.

I think a full-blown docs website would do much good to this package's adoption (both among internal & external users).

Should it, in the future, be added to `flutter_corelibrary`? see also https://github.com/leancodepl/flutter_corelibrary/issues/133

**Comment by iasiu** [comment]
> Offtop 1: I think a full-blown docs website would do much good to this package's adoption (both among internal & external users).

You are right, but maybe this package is not yet as popular to have that.

> Offtop 2: Should it, in the future, be added to `flutter_corelibrary`? see also [leancodepl/flutter_corelibrary#133](https://github.com/leancodepl/flutter_corelibrary/issues/133)

I think this package could be more independent, putting it there would sound like it's just for internal use.

**Comment by bartekpacia** [comment]
I agree with both :)

**Pull request merged**
